# Generated by Django 4.2.4 on 2023-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
